package com.teamb.statistic.models;

public enum StatisticType {
    PROJECT_COUNT_SYSTEM, DONATION_VALUE_SYSTEM,
    DONATION_VALUE_USER, PROJECT_COUNT_USER,
    DONOR_COUNT, NEW_DONOR_REGISTRATIONS
}