spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: userdata
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
  config:
    import: optional:file:.env[.properties]
