# services:
#   redis-primary:
#     image: redis:7.4
#     container_name: redis-primary
#     networks:
#       - redis-cluster
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis-primary-data:/data
#     command: ["redis-server", "--appendonly", "yes"]

#   redis-replica:
#     image: redis:7.4
#     container_name: redis-replica
#     networks:
#       - redis-cluster
#     depends_on:
#       - redis-primary
#     volumes:
#       - redis-replica-data:/data
#     command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-primary", "6379"]

#   redis-sentinel1:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: redis-sentinel1
#     networks:
#       - redis-cluster
#     depends_on:
#       - redis-primary
#     ports:
#       - "26379:26379"
#     volumes:
#     - ./sentinel.conf:/etc/redis/sentinel.conf


#   redis-sentinel2:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: redis-sentinel2
#     networks:
#       - redis-cluster
#     depends_on:
#       - redis-primary
#     volumes:
#       - ./sentinel.conf:/etc/redis/sentinel.conf


#   redis-sentinel3:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: redis-sentinel3
#     networks:
#       - redis-cluster
#     depends_on:
#       - redis-primary
#     volumes:
#       - ./sentinel.conf:/etc/redis/sentinel.conf  


# networks:
#   redis-cluster:
#     driver: bridge

# volumes:
#   redis-primary-data:
#   redis-replica-data:


#For testing
services:
  redis:
    image: redis:7.4
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes"]

  redis-backup:
    image: redis:7.4
    container_name: redis-backup
    ports:
      - "6380:6379"
    networks:
      - app-network
    depends_on:
      - redis
    command: ["redis-server", "--slaveof", "redis", "6379"]
    volumes:
      - redis-backup-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  redis-backup-data:
