services:
  redis-primary:
    image: redis:7.4
    container_name: redis-primary
    networks:
      - redis-cluster
    ports:
      - "6379:6379"
    volumes:
      - redis-primary-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-replica:
    image: redis:7.4
    container_name: redis-replica
    networks:
      - redis-cluster
    depends_on:
      - redis-primary
    volumes:
      - redis-replica-data:/data
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-primary", "6379"]

  redis-sentinel1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel1
    networks:
      - redis-cluster
    depends_on:
      - redis-primary
    ports:
      - "26379:26379"

  redis-sentinel2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel2
    networks:
      - redis-cluster
    depends_on:
      - redis-primary

  redis-sentinel3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel3
    networks:
      - redis-cluster
    depends_on:
      - redis-primary

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis-primary-data:
  redis-replica-data:
