spring:
  data:
    mongodb: 
      uri: mongodb+srv://nguyenmandat000:8B9A34Rnh0aMl5ZQ@charitydbproject.pikzz.mongodb.net/charitydbproject?retryWrites=true&w=majority&appName=CharityDBProject
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.charitan@gmail.com
    password: payi qdge xtwb pwnz
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env


  redis:
    host: redis-test
    port: 6379
  cache:
    type: redis

#Old mongodb url: mongodb+srv://donambinh2002:passw0rd@news.s0vit.mongodb.net/