# Use the official Redis image
FROM redis:7-alpine

# Copy custom Redis configuration (optional)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Default command to run Redis
CMD ["redis-server"]
